name: Pull Request lint

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

# This github action requires no permissions
permissions: {}

jobs:
  pull-request-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # check out the code so we can test the action
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./
