name: Pull Request lint

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

# This github action requires no permissions
permissions: {}

jobs:
  pull-request-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # check out the code so we can test the action
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./
